import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {pbkdf2Sync,randomBytes} from 'node:crypto';
import ts from 'typescript';
const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8');
async function moduleFrom(path,imports=''){
 const source=imports+'\n'+read(path).replace(/^import .*;\s*$/gm,'');
 const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
 return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
}
test('password auth: wrong password, secure session, old records, expiry, logout, rate limit and CSRF',async()=>{
 const db=new DatabaseSync(':memory:');db.exec(read('drizzle/0000_wide_starjammers.sql'));db.exec(read('drizzle/0001_fearless_stepford_cuckoos.sql'));
 db.exec(read('drizzle/0002_glossy_sheva_callister.sql'));db.exec(read('drizzle/0003_wild_night_nurse.sql'));db.exec(read('drizzle/0004_absurd_proemial_gods.sql'));
 const memoMigration=readdirSync(new URL('../drizzle',import.meta.url)).find(name=>name.startsWith('0005_')&&name.endsWith('.sql'));
 assert.ok(memoMigration,'memo migration is missing');db.exec(read('drizzle/'+memoMigration));
 const dailyMemoMigration=readdirSync(new URL('../drizzle',import.meta.url)).find(name=>name.startsWith('0006_')&&name.endsWith('.sql'));
 assert.ok(dailyMemoMigration,'daily memo migration is missing');db.exec(read('drizzle/'+dailyMemoMigration));
 const collapsedMemoMigration=readdirSync(new URL('../drizzle',import.meta.url)).find(name=>name.startsWith('0007_')&&name.endsWith('.sql'));
 assert.ok(collapsedMemoMigration,'collapsed memo migration is missing');db.exec(read('drizzle/'+collapsedMemoMigration));
 db.exec("CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT, username TEXT UNIQUE, password_hash TEXT, display_name TEXT NOT NULL DEFAULT '', role TEXT NOT NULL DEFAULT 'user', status TEXT NOT NULL, created INTEGER NOT NULL, updated INTEGER NOT NULL)");
 db.exec("CREATE TABLE signup_limits (id TEXT PRIMARY KEY, registered_at INTEGER NOT NULL)");
 db.exec("CREATE TABLE task_sessions (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, owner TEXT NOT NULL, start_at INTEGER NOT NULL, end_at INTEGER)");
 const spans=id=>db.prepare("SELECT start_at,end_at FROM task_sessions WHERE task_id=? ORDER BY start_at").all(id).map(s=>[s.start_at,s.end_at]);
 const adapter={prepare(sql){return {bind(...args){args=args.map(value=>typeof value==='boolean'?Number(value):value);return {async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return {meta:db.prepare(sql).run(...args)};}}},async all(){return {results:db.prepare(sql).all()};}};},async batch(items){return Promise.all(items.map(x=>x.run()));}};
 const salt=randomBytes(16),code='test-only-password';
 const storedHash='100000:'+salt.toString('hex')+':'+pbkdf2Sync(code,salt,100000,32,'sha256').toString('hex');
 db.prepare("INSERT INTO users (id,username,password_hash,status,created,updated) VALUES ('legacy-owner','legacy_user',?,'active',0,0)").run(storedHash);
 db.prepare("INSERT INTO tasks (id,owner,day,title,created) VALUES ('old','legacy-owner','2026-09-10','Existing record',0)").run();
 const env={APP_ORIGIN:'https://diary.test'};
 process.env.APP_ORIGIN=env.APP_ORIGIN;
 const helpers=await moduleFrom('lib/auth.ts');
 const dates=await moduleFrom('lib/work-dates.ts');
 globalThis.authFixture={...helpers,...dates,env,database:()=>adapter};
 const auth=await moduleFrom('app/api/auth/route.ts','const {env,database,clientAddress,hashToken,normalizeUsername,verifyPassword,sessionToken,sessionCookie,sameOrigin,SESSION_SECONDS,MAX_PASSWORD_LENGTH,UNKNOWN_USER_HASH}=globalThis.authFixture;');
 const signup=await moduleFrom('app/api/auth/signup/route.ts','const {database,clientAddress,createPasswordHash,hashToken,normalizeUsername,sessionCookie,sameOrigin,SESSION_SECONDS,MIN_PASSWORD_LENGTH,MAX_PASSWORD_LENGTH}=globalThis.authFixture;');
 const user=await moduleFrom('app/_auth/code-auth.ts','const {database,hashToken,sessionToken}=globalThis.authFixture;');
 globalThis.authFixture.getCodeUser=user.getCodeUser;
 const tasks=await moduleFrom('app/api/tasks/route.ts','const {getCodeUser,env,sameOrigin,database,validTimes}=globalThis.authFixture;');
 const calendar=await moduleFrom('app/api/calendar/route.ts','const {getCodeUser,database}=globalThis.authFixture;');
 let memos=null;try{memos=await moduleFrom('app/api/memos/route.ts','const {getCodeUser,env,sameOrigin,database}=globalThis.authFixture;');}catch{}
 assert.ok(memos?.GET&&memos?.POST,'memo API is missing');
 let dailyMemos=null;try{dailyMemos=await moduleFrom('app/api/daily-memos/route.ts','const {getCodeUser,env,sameOrigin,database,validDay}=globalThis.authFixture;');}catch{}
 assert.ok(dailyMemos?.GET&&dailyMemos?.POST,'daily memo API is missing');
 const request=(password,origin=env.APP_ORIGIN,ip='203.0.113.10',username='legacy_user')=>new Request(env.APP_ORIGIN+'/api/auth',{method:'POST',headers:{origin,'Content-Type':'application/json','x-forwarded-for':ip},body:JSON.stringify({username,password})});
 assert.equal((await tasks.GET(new Request(env.APP_ORIGIN+'/api/tasks?day=2026-09-10'))).status,401);
 assert.equal((await auth.POST(request(code,'https://evil.test'))).status,403);
 assert.equal((await auth.POST(request('incorrect'))).status,401);
 assert.equal((await auth.POST(request(code,env.APP_ORIGIN,'203.0.113.10','missing_user'))).status,401);
 assert.equal((await auth.POST(new Request(env.APP_ORIGIN+'/api/auth',{method:'POST',headers:{origin:env.APP_ORIGIN,'Content-Type':'application/json'},body:JSON.stringify({code})}))).status,400);
 const ok=await auth.POST(request(code,env.APP_ORIGIN,'203.0.113.10',' Legacy_User '));assert.equal(ok.status,200);
 const cookie=ok.headers.get('set-cookie');assert.match(cookie,/Secure; HttpOnly; SameSite=Strict/);
 const req=new Request(env.APP_ORIGIN+'/api/tasks?day=2026-09-10',{headers:{cookie}});
 assert.equal((await memos.GET(new Request(env.APP_ORIGIN+'/api/memos'))).status,401);
 assert.deepEqual(await user.getCodeUser(req),{userId:'legacy-owner'});
 const records=await tasks.GET(req);assert.equal(records.status,200);assert.equal((await records.json()).tasks[0].id,'old');
 assert.equal((await tasks.POST(new Request(req.url,{method:'POST',headers:{cookie,origin:'https://evil.test'},body:'{}'}))).status,403);
 assert.equal(await user.getCodeUser(new Request(req.url,{headers:{cookie:cookie.replace(/=./,'=z')}})),null);
 const signupRequest=(username,password='new-password',confirmation=password,ip='192.0.2.10')=>new Request(env.APP_ORIGIN+'/api/auth/signup',{method:'POST',headers:{origin:env.APP_ORIGIN,'Content-Type':'application/json','x-forwarded-for':ip},body:JSON.stringify({username,password,confirmation})});
 assert.equal((await signup.POST(signupRequest('abc'))).status,400);
 assert.equal((await signup.POST(signupRequest('new-user'))).status,400);
 assert.equal((await signup.POST(signupRequest('new_user','short'))).status,400);
 assert.equal((await signup.POST(signupRequest('new_user','new-password','different'))).status,400);
 const signupStart=Date.now(),originalSignupNow=Date.now;Date.now=()=>signupStart;
 try{
  const joined=await signup.POST(signupRequest('new_user'));assert.equal(joined.status,201);assert.match(joined.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Strict/);
  const joinedUser=db.prepare("SELECT id,password_hash FROM users WHERE username='new_user'").get();assert.ok(joinedUser?.id);assert.match(joinedUser.password_hash,/^100000:[a-f0-9]{32}:[a-f0-9]{64}$/);
  assert.equal((await signup.POST(signupRequest('another_user'))).status,429);
  assert.equal((await signup.POST(signupRequest('NEW_USER','new-password','new-password','192.0.2.11'))).status,409);
  const signupAttackIp='192.0.2.20';
  for(let attempt=1;attempt<5;attempt++)assert.equal((await signup.POST(signupRequest('new_user','new-password','new-password',signupAttackIp))).status,409);
  const signupBlocked=await signup.POST(signupRequest('new_user','new-password','new-password',signupAttackIp));assert.equal(signupBlocked.status,429);assert.equal(signupBlocked.headers.get('retry-after'),'900');
  assert.equal((await auth.POST(request('new-password',env.APP_ORIGIN,signupAttackIp,'new_user'))).status,429);
  assert.equal((await auth.POST(request(code,env.APP_ORIGIN,'192.0.2.12','new_user'))).status,401);
  const newLogin=await auth.POST(request('new-password',env.APP_ORIGIN,'192.0.2.13','new_user'));assert.equal(newLogin.status,200);
  assert.deepEqual(await user.getCodeUser(new Request(req.url,{headers:{cookie:newLogin.headers.get('set-cookie')}})),{userId:joinedUser.id});
  Date.now=()=>signupStart+24*60*60_000;
  assert.equal((await signup.POST(signupRequest('next_day_user'))).status,201);
 }finally{Date.now=originalSignupNow;}
 const post=body=>tasks.POST(new Request(req.url,{method:'POST',headers:{cookie,origin:env.APP_ORIGIN},body:JSON.stringify(body)}));
 const memoReq=new Request(env.APP_ORIGIN+'/api/memos',{headers:{cookie}});
 const postMemo=body=>memos.POST(new Request(memoReq.url,{method:'POST',headers:{cookie,origin:env.APP_ORIGIN,'Content-Type':'application/json'},body:JSON.stringify(body)}));
 const dailyMemoReq=day=>new Request(env.APP_ORIGIN+'/api/daily-memos?day='+day,{headers:{cookie}});
 const postDailyMemo=body=>dailyMemos.POST(new Request(env.APP_ORIGIN+'/api/daily-memos',{method:'POST',headers:{cookie,origin:env.APP_ORIGIN,'Content-Type':'application/json'},body:JSON.stringify(body)}));
 const base=Date.now(),originalNow=Date.now;let current=base;
 Date.now=()=>current;
 try{
 assert.equal((await post({action:'create',title:'timer',note:'진행 내용',result:'',target:3600000,day:'2026-09-10',elapsed:0,run:true})).status,200);
 let timer=db.prepare("SELECT * FROM tasks WHERE title='timer'").get();const id=timer.id;
 assert.equal(timer.started_at,base);assert.equal(timer.ended_at,null);assert.equal(timer.target,3600000);
 current=base+3000;assert.equal((await post({action:'pause',id,version:0})).status,200);
 current=base+10000;assert.equal((await post({action:'resume',id,version:1})).status,200);
 timer=db.prepare('SELECT * FROM tasks WHERE id=?').get(id);assert.equal(timer.started_at,base);
 current=base+14000;
 const calReq=new Request(env.APP_ORIGIN+'/api/calendar?month=2026-09',{headers:{cookie}});
 assert.equal((await calendar.GET(new Request(calReq.url))).status,401);
 let cal=await (await calendar.GET(calReq)).json();assert.equal(cal.days[0].count,2);assert.equal(cal.days[0].total,7000);assert.equal(cal.days[0].running,1);
 assert.equal((await post({action:'finish',id,version:2,result:'배포 확인 완료'})).status,200);
 timer=db.prepare('SELECT * FROM tasks WHERE id=?').get(id);assert.equal(timer.started_at,base);assert.equal(timer.ended_at,base+14000);assert.equal(timer.elapsed,7000);assert.equal(timer.result,'배포 확인 완료');
 assert.deepEqual(spans(id),[[base,base+3000],[base+10000,base+14000]]);
 assert.deepEqual((await (await tasks.GET(req)).json()).tasks.find(x=>x.id===id).sessions,[{start_at:base,end_at:base+3000},{start_at:base+10000,end_at:base+14000}]);
 current=base+20000;cal=await (await calendar.GET(calReq)).json();assert.equal(cal.days[0].total,7000);assert.equal(cal.days[0].running,0);
 const manual={action:'create',title:'manual',note:'업무 메모',result:'문서 작성 완료',target:1800000,day:'2026-08-31',elapsed:60000,run:false,started_at:base,ended_at:base+60000};
 assert.equal((await post({...manual,ended_at:base-1})).status,400);
 assert.equal((await post(manual)).status,200);assert.deepEqual({...db.prepare("SELECT result,target FROM tasks WHERE title='manual'").get()},{result:'문서 작성 완료',target:1800000});
 const manualTimer=db.prepare("SELECT * FROM tasks WHERE title='manual'").get();
 current=base+21000;
 const reopen={...manual,action:'edit',id:manualTimer.id,version:manualTimer.version,elapsed:90000,run:true};
 assert.equal((await post(reopen)).status,200);
 let reopened=db.prepare('SELECT * FROM tasks WHERE id=?').get(manualTimer.id);
 assert.deepEqual({status:reopened.status,elapsed:reopened.elapsed,started:reopened.started,started_at:reopened.started_at,ended_at:reopened.ended_at},{status:'running',elapsed:90000,started:current,started_at:base,ended_at:null});
 assert.equal((await post(reopen)).status,409);
 current=base+26000;assert.equal((await post({action:'finish',id:manualTimer.id,version:1,result:'추가 작업 완료'})).status,200);
 reopened=db.prepare('SELECT * FROM tasks WHERE id=?').get(manualTimer.id);assert.equal(reopened.elapsed,95000);assert.equal(reopened.ended_at,current);
 assert.deepEqual(spans(manualTimer.id),[[base,base+60000],[base+21000,base+26000]]);
 cal=await (await calendar.GET(calReq)).json();assert.equal(cal.days.length,1);assert.equal(cal.days[0].count,2);
 assert.equal((await calendar.GET(new Request(env.APP_ORIGIN+'/api/calendar?month=2026-13',{headers:{cookie}}))).status,400);
 const empty=await (await calendar.GET(new Request(env.APP_ORIGIN+'/api/calendar?month=2026-07',{headers:{cookie}}))).json();assert.equal(empty.days.length,0);
 assert.deepEqual({...db.prepare("SELECT started_at,target FROM tasks WHERE id='old'").get()},{started_at:null,target:0});
 assert.equal(dates.parseTimeInput('2026-09-10T09:00:00'),Date.parse('2026-09-10T00:00:00Z'));
 assert.equal(dates.timeInput(Date.parse('2026-09-10T00:00:00Z')),'2026-09-10T09:00:00');
 assert.equal(dates.timeLabel(Date.parse('2026-09-15T00:00:00Z')),'09:00');
 assert.equal(dates.timeLabel(null),'미기록');
 let response=await postMemo({action:'create'});assert.equal(response.status,200);
 let created=(await response.json()).memo;assert.equal(created.title,'');assert.equal(created.body,'');assert.equal(created.collapsed,false);assert.equal(created.version,0);
 response=await postMemo({action:'update',id:created.id,version:0,title:'항상 보이는 메모',body:'날짜와 무관한 내용',collapsed:true});
 assert.equal(response.status,200);let updated=(await response.json()).memo;assert.equal(updated.version,1);assert.equal(updated.collapsed,true);assert.equal(db.prepare('SELECT collapsed FROM memos WHERE id=?').get(created.id).collapsed,1);
 response=await postMemo({action:'update',id:created.id,version:0,title:'오래된 수정',body:''});
 assert.equal(response.status,409);assert.equal((await response.json()).currentVersion,1);
 assert.equal((await postMemo({action:'update',id:created.id,version:1,title:'x'.repeat(201),body:''})).status,400);
 assert.equal((await postMemo({action:'update',id:created.id,version:1,title:'메모',body:'',collapsed:'yes'})).status,400);
 response=await memos.GET(new Request(env.APP_ORIGIN+'/api/memos?day=1999-01-01',{headers:{cookie}}));
 assert.equal(response.status,200);const savedMemo=(await response.json()).memos[0];assert.equal(savedMemo.title,'항상 보이는 메모');assert.equal(savedMemo.collapsed,true);
 current+=1;response=await postMemo({action:'create'});const secondMemo=(await response.json()).memo;
 current+=1;response=await postMemo({action:'create'});const thirdMemo=(await response.json()).memo;
 let memoOrder=(await (await memos.GET(memoReq)).json()).memos.map(memo=>memo.id);assert.deepEqual(memoOrder,[created.id,secondMemo.id,thirdMemo.id]);
 assert.equal((await postMemo({action:'reorder',id:created.id,swapId:secondMemo.id})).status,200);
 memoOrder=(await (await memos.GET(memoReq)).json()).memos.map(memo=>memo.id);assert.deepEqual(memoOrder,[secondMemo.id,created.id,thirdMemo.id]);
 assert.equal((await postMemo({action:'reorder',id:thirdMemo.id,swapId:created.id})).status,200);
 memoOrder=(await (await memos.GET(memoReq)).json()).memos.map(memo=>memo.id);assert.deepEqual(memoOrder,[secondMemo.id,thirdMemo.id,created.id]);
 assert.equal((await postMemo({action:'reorder',id:created.id,swapId:created.id})).status,400);
 db.prepare("INSERT INTO memos (id,owner,title,body,position,created,updated) VALUES ('other-memo','another','숨김','','2',0,0)").run();
 assert.equal((await postMemo({action:'reorder',id:created.id,swapId:'other-memo'})).status,404);
 response=await memos.GET(memoReq);assert.deepEqual((await response.json()).memos.map(memo=>memo.id),memoOrder);
 assert.equal((await postMemo({action:'delete',id:created.id,version:1})).status,200);
 assert.equal((await postMemo({action:'delete',id:secondMemo.id,version:0})).status,200);
 assert.equal((await postMemo({action:'delete',id:thirdMemo.id,version:0})).status,200);
 response=await memos.GET(memoReq);assert.equal((await response.json()).memos.length,0);
 response=await postDailyMemo({action:'create',day:'2026-09-10'});assert.equal(response.status,200);
 const dailyCreated=(await response.json()).memo;
 response=await postDailyMemo({action:'update',day:'2026-09-10',id:dailyCreated.id,version:0,title:'오늘 메모',body:'오늘만 표시'});assert.equal(response.status,200);
 current+=1;response=await postDailyMemo({action:'create',day:'2026-09-10'});const secondDaily=(await response.json()).memo;
 assert.equal((await postDailyMemo({action:'reorder',day:'2026-09-10',id:dailyCreated.id,swapId:secondDaily.id})).status,200);
 response=await dailyMemos.GET(dailyMemoReq('2026-09-10'));let dailyOrder=(await response.json()).memos;assert.deepEqual(dailyOrder.map(memo=>memo.id),[secondDaily.id,dailyCreated.id]);assert.equal(dailyOrder[1].title,'오늘 메모');
 assert.equal((await postDailyMemo({action:'reorder',day:'2026-09-10',id:dailyCreated.id,swapId:dailyCreated.id})).status,400);
 response=await dailyMemos.GET(dailyMemoReq('2026-09-11'));assert.equal((await response.json()).memos.length,0);
 current+=1;response=await postDailyMemo({action:'create',day:'2026-09-11'});const otherDayMemo=(await response.json()).memo;
 assert.equal((await postDailyMemo({action:'reorder',day:'2026-09-10',id:dailyCreated.id,swapId:otherDayMemo.id})).status,404);
 dailyOrder=(await (await dailyMemos.GET(dailyMemoReq('2026-09-10'))).json()).memos;assert.deepEqual(dailyOrder.map(memo=>memo.id),[secondDaily.id,dailyCreated.id]);
 assert.equal((await dailyMemos.GET(dailyMemoReq('invalid'))).status,400);
 }finally{Date.now=originalNow;}
 const account=await moduleFrom('app/api/account/route.ts','const {getCodeUser,database,createPasswordHash,hashToken,verifyPassword,sessionToken,sameOrigin,MIN_PASSWORD_LENGTH,MAX_PASSWORD_LENGTH}=globalThis.authFixture;');
 const accountPost=(body,sessionCookie,origin=env.APP_ORIGIN)=>account.POST(new Request(env.APP_ORIGIN+'/api/account',{method:'POST',headers:{cookie:sessionCookie,origin,'Content-Type':'application/json'},body:JSON.stringify(body)}));
 const otherOwner=db.prepare("SELECT id FROM users WHERE username='new_user'").get().id;
 const otherLogin=ip=>auth.POST(request('new-password',env.APP_ORIGIN,ip,'new_user'));
 const otherCookie=(await otherLogin('192.0.2.30')).headers.get('set-cookie'),otherDevice=(await otherLogin('192.0.2.31')).headers.get('set-cookie');
 const countOf=(table,owner)=>db.prepare(`SELECT COUNT(*) AS n FROM ${table} WHERE owner=?`).get(owner).n;
 for(const [owner,suffix] of [[otherOwner,'other'],['legacy-owner','legacy']]){
  db.prepare("INSERT INTO tasks (id,owner,day,title,created) VALUES (?,?,'2026-09-10','Account record',0)").run('account-task-'+suffix,owner);
  db.prepare("INSERT INTO memos (id,owner,position,created,updated) VALUES (?,?,0,0,0)").run('account-memo-'+suffix,owner);
  db.prepare("INSERT INTO daily_memos (id,owner,day,position,created,updated) VALUES (?,?,'2026-09-10',0,0,0)").run('account-daily-'+suffix,owner);
 }
 assert.equal((await account.POST(new Request(env.APP_ORIGIN+'/api/account',{method:'POST',headers:{origin:env.APP_ORIGIN},body:JSON.stringify({action:'verify',password:'new-password'})}))).status,401);
 assert.equal((await accountPost({action:'verify',password:'new-password'},otherCookie,'https://evil.test')).status,403);
 assert.equal((await accountPost({action:'verify',password:'incorrect'},otherCookie)).status,401);
 assert.equal((await accountPost({action:'constructor',password:'new-password'},otherCookie)).status,400);
 assert.equal((await accountPost({action:'verify',password:'new-password'},otherCookie)).status,200);
 assert.equal((await accountPost({action:'delete-memos',password:'incorrect'},otherCookie)).status,401);assert.equal(countOf('memos',otherOwner),1);
 for(const [action,table] of [['delete-memos','memos'],['delete-daily-memos','daily_memos'],['delete-tasks','tasks']]){
  const legacyCount=countOf(table,'legacy-owner');
  assert.equal((await accountPost({action,password:'new-password'},otherCookie)).status,200);
  assert.equal(countOf(table,otherOwner),0);assert.equal(countOf(table,'legacy-owner'),legacyCount);
 }
 assert.equal((await accountPost({action:'change-password',password:'new-password',newPassword:'short',confirmation:'short'},otherCookie)).status,400);
 assert.equal((await accountPost({action:'change-password',password:'new-password',newPassword:'changed-password',confirmation:'different'},otherCookie)).status,400);
 assert.equal((await accountPost({action:'change-password',password:'new-password',newPassword:'changed-password',confirmation:'changed-password'},otherCookie)).status,200);
 assert.deepEqual(await user.getCodeUser(new Request(req.url,{headers:{cookie:otherCookie}})),{userId:otherOwner});
 assert.equal(await user.getCodeUser(new Request(req.url,{headers:{cookie:otherDevice}})),null);
 assert.deepEqual(await user.getCodeUser(req),{userId:'legacy-owner'});
 assert.equal((await otherLogin('192.0.2.32')).status,401);
 assert.equal((await auth.POST(request('changed-password',env.APP_ORIGIN,'192.0.2.33','new_user'))).status,200);
 for(let attempt=1;attempt<5;attempt++)assert.equal((await accountPost({action:'verify',password:'incorrect'},otherCookie)).status,401);
 const accountBlocked=await accountPost({action:'verify',password:'incorrect'},otherCookie);assert.equal(accountBlocked.status,429);assert.equal(accountBlocked.headers.get('retry-after'),'900');
 assert.equal((await accountPost({action:'verify',password:'changed-password'},otherCookie)).status,429);
 db.prepare("DELETE FROM code_limits WHERE id LIKE 'account:%'").run();db.prepare("DELETE FROM tasks WHERE id='account-task-legacy'").run();
 db.prepare('UPDATE code_sessions SET expires=0').run();assert.equal(await user.getCodeUser(req),null);
 const again=await auth.POST(request(code));const c2=again.headers.get('set-cookie');
 const logout=await auth.DELETE(new Request(env.APP_ORIGIN+'/api/auth',{method:'DELETE',headers:{origin:env.APP_ORIGIN,cookie:c2}}));assert.equal(logout.status,200);assert.match(logout.headers.get('set-cookie'),/Max-Age=0/);
 assert.equal(await user.getCodeUser(new Request(req.url,{headers:{cookie:c2}})),null);
 const attackIp='198.51.100.22';
 const rateStart=Date.now();Date.now=()=>rateStart;
 try{
  for(let attempt=1;attempt<5;attempt++)assert.equal((await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp))).status,401);
  let blocked=await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp));assert.equal(blocked.status,429);assert.equal(blocked.headers.get('retry-after'),'900');
  assert.equal((await auth.POST(request(code,env.APP_ORIGIN,attackIp))).status,429);
  const storedLimit=db.prepare('SELECT id,attempts FROM code_limits WHERE attempts=5').get();assert.equal(storedLimit.attempts,5);assert.match(storedLimit.id,/^ip:[a-f0-9]{64}$/);assert.ok(!storedLimit.id.includes(attackIp));
  assert.equal((await auth.POST(request(code,env.APP_ORIGIN,'198.51.100.23'))).status,200);
  Date.now=()=>rateStart+900001;
  for(let attempt=6;attempt<10;attempt++)assert.equal((await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp))).status,401);
  blocked=await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp));assert.equal(blocked.status,429);assert.equal(blocked.headers.get('retry-after'),'4500');
 }finally{Date.now=originalNow;}
 assert.equal(db.prepare('SELECT owner FROM tasks').get().owner,'legacy-owner');
 db.close();delete globalThis.authFixture;delete process.env.APP_ORIGIN;
});
