import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {pbkdf2Sync,randomBytes} from 'node:crypto';
import ts from 'typescript';
const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8');
async function moduleFrom(path,imports=''){
 const source=imports+'\n'+read(path).replace(/^import .*;\s*$/gm,'');
 const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
 return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
}
test('code auth: wrong code, secure session, old records, expiry, logout, rate limit and CSRF',async()=>{
 const db=new DatabaseSync(':memory:');db.exec(read('drizzle/0000_wide_starjammers.sql'));db.exec(read('drizzle/0001_fearless_stepford_cuckoos.sql'));
 db.exec(read('drizzle/0002_glossy_sheva_callister.sql'));db.exec(read('drizzle/0003_wild_night_nurse.sql'));db.exec(read('drizzle/0004_absurd_proemial_gods.sql'));
 const memoMigration=readdirSync(new URL('../drizzle',import.meta.url)).find(name=>name.startsWith('0005_')&&name.endsWith('.sql'));
 assert.ok(memoMigration,'memo migration is missing');db.exec(read('drizzle/'+memoMigration));
 const dailyMemoMigration=readdirSync(new URL('../drizzle',import.meta.url)).find(name=>name.startsWith('0006_')&&name.endsWith('.sql'));
 assert.ok(dailyMemoMigration,'daily memo migration is missing');db.exec(read('drizzle/'+dailyMemoMigration));
 const collapsedMemoMigration=readdirSync(new URL('../drizzle',import.meta.url)).find(name=>name.startsWith('0007_')&&name.endsWith('.sql'));
 assert.ok(collapsedMemoMigration,'collapsed memo migration is missing');db.exec(read('drizzle/'+collapsedMemoMigration));
 db.exec("CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT, access_code_hash TEXT, access_code_lookup TEXT UNIQUE, display_name TEXT NOT NULL DEFAULT '', role TEXT NOT NULL DEFAULT 'user', status TEXT NOT NULL, created INTEGER NOT NULL, updated INTEGER NOT NULL)");
 db.exec("CREATE TABLE signup_limits (id TEXT PRIMARY KEY, registered_at INTEGER NOT NULL)");
 const adapter={prepare(sql){return {bind(...args){args=args.map(value=>typeof value==='boolean'?Number(value):value);return {async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return {meta:db.prepare(sql).run(...args)};}}},async all(){return {results:db.prepare(sql).all()};}};},async batch(items){return Promise.all(items.map(x=>x.run()));}};
 const salt=randomBytes(16),code='test-only-code';
 const storedHash='100000:'+salt.toString('hex')+':'+pbkdf2Sync(code,salt,100000,32,'sha256').toString('hex');
 db.prepare("INSERT INTO users (id,access_code_hash,status,created,updated) VALUES ('legacy-owner',?,'active',0,0)").run(storedHash);
 db.prepare("INSERT INTO tasks (id,owner,day,title,created) VALUES ('old','legacy-owner','2026-09-10','Existing record',0)").run();
 const env={APP_ORIGIN:'https://diary.test'};
 process.env.APP_ORIGIN=env.APP_ORIGIN;
 process.env.ACCESS_CODE_SECRET='test-only-access-code-secret-32-characters';
 const helpers=await moduleFrom('lib/access-code.ts');
 const dates=await moduleFrom('lib/work-dates.ts');
 globalThis.authFixture={...helpers,...dates,env,database:()=>adapter};
 const auth=await moduleFrom('app/api/auth/route.ts','const {env,database,clientAddress,codeLookup,hashToken,verifyCode,sessionToken,sessionCookie,sameOrigin,SESSION_SECONDS}=globalThis.authFixture;');
 const signup=await moduleFrom('app/api/auth/signup/route.ts','const {database,clientAddress,codeLookup,createCodeHash,hashToken,sessionCookie,sameOrigin,SESSION_SECONDS,verifyCode,MIN_CODE_LENGTH}=globalThis.authFixture;');
 const user=await moduleFrom('app/_auth/code-auth.ts','const {database,hashToken,sessionToken}=globalThis.authFixture;');
 globalThis.authFixture.getCodeUser=user.getCodeUser;
 const tasks=await moduleFrom('app/api/tasks/route.ts','const {getCodeUser,env,sameOrigin,database,validTimes}=globalThis.authFixture;');
 const calendar=await moduleFrom('app/api/calendar/route.ts','const {getCodeUser,database}=globalThis.authFixture;');
 let memos=null;try{memos=await moduleFrom('app/api/memos/route.ts','const {getCodeUser,env,sameOrigin,database}=globalThis.authFixture;');}catch{}
 assert.ok(memos?.GET&&memos?.POST,'memo API is missing');
 let dailyMemos=null;try{dailyMemos=await moduleFrom('app/api/daily-memos/route.ts','const {getCodeUser,env,sameOrigin,database,validDay}=globalThis.authFixture;');}catch{}
 assert.ok(dailyMemos?.GET&&dailyMemos?.POST,'daily memo API is missing');
 const request=(value,origin=env.APP_ORIGIN,ip='203.0.113.10')=>new Request(env.APP_ORIGIN+'/api/auth',{method:'POST',headers:{origin,'Content-Type':'application/json','x-forwarded-for':ip},body:JSON.stringify({code:value})});
 assert.equal((await tasks.GET(new Request(env.APP_ORIGIN+'/api/tasks?day=2026-09-10'))).status,401);
 assert.equal((await auth.POST(request(code,'https://evil.test'))).status,403);
 assert.equal((await auth.POST(request('incorrect'))).status,401);
 const ok=await auth.POST(request(code));assert.equal(ok.status,200);
 const cookie=ok.headers.get('set-cookie');assert.match(cookie,/Secure; HttpOnly; SameSite=Strict/);
 assert.match(db.prepare("SELECT access_code_lookup FROM users WHERE id='legacy-owner'").get().access_code_lookup,/^[a-f0-9]{64}$/);
 const req=new Request(env.APP_ORIGIN+'/api/tasks?day=2026-09-10',{headers:{cookie}});
 assert.equal((await memos.GET(new Request(env.APP_ORIGIN+'/api/memos'))).status,401);
 assert.deepEqual(await user.getCodeUser(req),{userId:'legacy-owner'});
 const records=await tasks.GET(req);assert.equal(records.status,200);assert.equal((await records.json()).tasks[0].id,'old');
 assert.equal((await tasks.POST(new Request(req.url,{method:'POST',headers:{cookie,origin:'https://evil.test'},body:'{}'}))).status,403);
 assert.equal(await user.getCodeUser(new Request(req.url,{headers:{cookie:cookie.replace(/=./,'=z')}})),null);
 const signupRequest=(newCode,confirmation=newCode,ip='192.0.2.10')=>new Request(env.APP_ORIGIN+'/api/auth/signup',{method:'POST',headers:{origin:env.APP_ORIGIN,'Content-Type':'application/json','x-forwarded-for':ip},body:JSON.stringify({code:newCode,confirmation})});
 assert.equal((await signup.POST(signupRequest('four'))).status,400);
 assert.equal((await signup.POST(signupRequest('new-code','different'))).status,400);
 const signupStart=Date.now(),originalSignupNow=Date.now;Date.now=()=>signupStart;
 try{
  const joined=await signup.POST(signupRequest('new-code'));assert.equal(joined.status,201);assert.match(joined.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Strict/);
  const joinedUser=db.prepare("SELECT id FROM users WHERE access_code_lookup IS NOT NULL AND id<>'legacy-owner' ORDER BY created LIMIT 1").get();assert.ok(joinedUser?.id);
  assert.equal((await signup.POST(signupRequest('another-code'))).status,429);
  assert.equal((await signup.POST(signupRequest('new-code','new-code','192.0.2.11'))).status,409);
  const signupAttackIp='192.0.2.20';
  for(let attempt=1;attempt<5;attempt++)assert.equal((await signup.POST(signupRequest('new-code','new-code',signupAttackIp))).status,409);
  const signupBlocked=await signup.POST(signupRequest('new-code','new-code',signupAttackIp));assert.equal(signupBlocked.status,429);assert.equal(signupBlocked.headers.get('retry-after'),'900');
  assert.equal((await auth.POST(request('new-code',env.APP_ORIGIN,signupAttackIp))).status,429);
  const newLogin=await auth.POST(request('new-code',env.APP_ORIGIN,'192.0.2.12'));assert.equal(newLogin.status,200);
  assert.deepEqual(await user.getCodeUser(new Request(req.url,{headers:{cookie:newLogin.headers.get('set-cookie')}})),{userId:joinedUser.id});
  Date.now=()=>signupStart+24*60*60_000;
  assert.equal((await signup.POST(signupRequest('next-day-code'))).status,201);
 }finally{Date.now=originalSignupNow;}
 const post=body=>tasks.POST(new Request(req.url,{method:'POST',headers:{cookie,origin:env.APP_ORIGIN},body:JSON.stringify(body)}));
 const memoReq=new Request(env.APP_ORIGIN+'/api/memos',{headers:{cookie}});
 const postMemo=body=>memos.POST(new Request(memoReq.url,{method:'POST',headers:{cookie,origin:env.APP_ORIGIN,'Content-Type':'application/json'},body:JSON.stringify(body)}));
 const dailyMemoReq=day=>new Request(env.APP_ORIGIN+'/api/daily-memos?day='+day,{headers:{cookie}});
 const postDailyMemo=body=>dailyMemos.POST(new Request(env.APP_ORIGIN+'/api/daily-memos',{method:'POST',headers:{cookie,origin:env.APP_ORIGIN,'Content-Type':'application/json'},body:JSON.stringify(body)}));
 const base=Date.now(),originalNow=Date.now;let current=base;
 Date.now=()=>current;
 try{
 assert.equal((await post({action:'create',title:'timer',note:'진행 내용',result:'',target:3600000,day:'2026-09-10',elapsed:0,run:true})).status,200);
 let timer=db.prepare("SELECT * FROM tasks WHERE title='timer'").get();const id=timer.id;
 assert.equal(timer.started_at,base);assert.equal(timer.ended_at,null);assert.equal(timer.target,3600000);
 current=base+3000;assert.equal((await post({action:'pause',id,version:0})).status,200);
 current=base+10000;assert.equal((await post({action:'resume',id,version:1})).status,200);
 timer=db.prepare('SELECT * FROM tasks WHERE id=?').get(id);assert.equal(timer.started_at,base);
 current=base+14000;
 const calReq=new Request(env.APP_ORIGIN+'/api/calendar?month=2026-09',{headers:{cookie}});
 assert.equal((await calendar.GET(new Request(calReq.url))).status,401);
 let cal=await (await calendar.GET(calReq)).json();assert.equal(cal.days[0].count,2);assert.equal(cal.days[0].total,7000);assert.equal(cal.days[0].running,1);
 assert.equal((await post({action:'finish',id,version:2,result:'배포 확인 완료'})).status,200);
 timer=db.prepare('SELECT * FROM tasks WHERE id=?').get(id);assert.equal(timer.started_at,base);assert.equal(timer.ended_at,base+14000);assert.equal(timer.elapsed,7000);assert.equal(timer.result,'배포 확인 완료');
 current=base+20000;cal=await (await calendar.GET(calReq)).json();assert.equal(cal.days[0].total,7000);assert.equal(cal.days[0].running,0);
 const manual={action:'create',title:'manual',note:'업무 메모',result:'문서 작성 완료',target:1800000,day:'2026-08-31',elapsed:60000,run:false,started_at:base,ended_at:base+60000};
 assert.equal((await post({...manual,ended_at:base-1})).status,400);
 assert.equal((await post(manual)).status,200);assert.deepEqual({...db.prepare("SELECT result,target FROM tasks WHERE title='manual'").get()},{result:'문서 작성 완료',target:1800000});
 const manualTimer=db.prepare("SELECT * FROM tasks WHERE title='manual'").get();
 current=base+21000;
 const reopen={...manual,action:'edit',id:manualTimer.id,version:manualTimer.version,elapsed:90000,run:true};
 assert.equal((await post(reopen)).status,200);
 let reopened=db.prepare('SELECT * FROM tasks WHERE id=?').get(manualTimer.id);
 assert.deepEqual({status:reopened.status,elapsed:reopened.elapsed,started:reopened.started,started_at:reopened.started_at,ended_at:reopened.ended_at},{status:'running',elapsed:90000,started:current,started_at:base,ended_at:null});
 assert.equal((await post(reopen)).status,409);
 current=base+26000;assert.equal((await post({action:'finish',id:manualTimer.id,version:1,result:'추가 작업 완료'})).status,200);
 reopened=db.prepare('SELECT * FROM tasks WHERE id=?').get(manualTimer.id);assert.equal(reopened.elapsed,95000);assert.equal(reopened.ended_at,current);
 cal=await (await calendar.GET(calReq)).json();assert.equal(cal.days.length,1);assert.equal(cal.days[0].count,2);
 assert.equal((await calendar.GET(new Request(env.APP_ORIGIN+'/api/calendar?month=2026-13',{headers:{cookie}}))).status,400);
 const empty=await (await calendar.GET(new Request(env.APP_ORIGIN+'/api/calendar?month=2026-07',{headers:{cookie}}))).json();assert.equal(empty.days.length,0);
 assert.deepEqual({...db.prepare("SELECT started_at,target FROM tasks WHERE id='old'").get()},{started_at:null,target:0});
 assert.equal(dates.parseTimeInput('2026-09-10T09:00:00'),Date.parse('2026-09-10T00:00:00Z'));
 assert.equal(dates.timeInput(Date.parse('2026-09-10T00:00:00Z')),'2026-09-10T09:00:00');
 assert.equal(dates.timeLabel(Date.parse('2026-09-15T00:00:00Z')),'09:00');
 assert.equal(dates.timeLabel(null),'미기록');
 let response=await postMemo({action:'create'});assert.equal(response.status,200);
 let created=(await response.json()).memo;assert.equal(created.title,'');assert.equal(created.body,'');assert.equal(created.collapsed,false);assert.equal(created.version,0);
 response=await postMemo({action:'update',id:created.id,version:0,title:'항상 보이는 메모',body:'날짜와 무관한 내용',collapsed:true});
 assert.equal(response.status,200);let updated=(await response.json()).memo;assert.equal(updated.version,1);assert.equal(updated.collapsed,true);assert.equal(db.prepare('SELECT collapsed FROM memos WHERE id=?').get(created.id).collapsed,1);
 response=await postMemo({action:'update',id:created.id,version:0,title:'오래된 수정',body:''});
 assert.equal(response.status,409);assert.equal((await response.json()).currentVersion,1);
 assert.equal((await postMemo({action:'update',id:created.id,version:1,title:'x'.repeat(201),body:''})).status,400);
 assert.equal((await postMemo({action:'update',id:created.id,version:1,title:'메모',body:'',collapsed:'yes'})).status,400);
 response=await memos.GET(new Request(env.APP_ORIGIN+'/api/memos?day=1999-01-01',{headers:{cookie}}));
 assert.equal(response.status,200);const savedMemo=(await response.json()).memos[0];assert.equal(savedMemo.title,'항상 보이는 메모');assert.equal(savedMemo.collapsed,true);
 db.prepare("INSERT INTO memos (id,owner,title,body,position,created,updated) VALUES ('other-memo','another','숨김','','2',0,0)").run();
 response=await memos.GET(memoReq);assert.equal((await response.json()).memos.length,1);
 assert.equal((await postMemo({action:'delete',id:created.id,version:1})).status,200);
 response=await memos.GET(memoReq);assert.equal((await response.json()).memos.length,0);
 response=await postDailyMemo({action:'create',day:'2026-09-10'});assert.equal(response.status,200);
 const dailyCreated=(await response.json()).memo;
 response=await postDailyMemo({action:'update',day:'2026-09-10',id:dailyCreated.id,version:0,title:'오늘 메모',body:'오늘만 표시'});assert.equal(response.status,200);
 response=await dailyMemos.GET(dailyMemoReq('2026-09-10'));assert.equal((await response.json()).memos[0].title,'오늘 메모');
 response=await dailyMemos.GET(dailyMemoReq('2026-09-11'));assert.equal((await response.json()).memos.length,0);
 assert.equal((await dailyMemos.GET(dailyMemoReq('invalid'))).status,400);
 }finally{Date.now=originalNow;}
 db.prepare('UPDATE code_sessions SET expires=0').run();assert.equal(await user.getCodeUser(req),null);
 const again=await auth.POST(request(code));const c2=again.headers.get('set-cookie');
 const logout=await auth.DELETE(new Request(env.APP_ORIGIN+'/api/auth',{method:'DELETE',headers:{origin:env.APP_ORIGIN,cookie:c2}}));assert.equal(logout.status,200);assert.match(logout.headers.get('set-cookie'),/Max-Age=0/);
 assert.equal(await user.getCodeUser(new Request(req.url,{headers:{cookie:c2}})),null);
 const attackIp='198.51.100.22';
 const rateStart=Date.now();Date.now=()=>rateStart;
 try{
  for(let attempt=1;attempt<5;attempt++)assert.equal((await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp))).status,401);
  let blocked=await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp));assert.equal(blocked.status,429);assert.equal(blocked.headers.get('retry-after'),'900');
  assert.equal((await auth.POST(request(code,env.APP_ORIGIN,attackIp))).status,429);
  const storedLimit=db.prepare('SELECT id,attempts FROM code_limits WHERE attempts=5').get();assert.equal(storedLimit.attempts,5);assert.match(storedLimit.id,/^ip:[a-f0-9]{64}$/);assert.ok(!storedLimit.id.includes(attackIp));
  assert.equal((await auth.POST(request(code,env.APP_ORIGIN,'198.51.100.23'))).status,200);
  Date.now=()=>rateStart+900001;
  for(let attempt=6;attempt<10;attempt++)assert.equal((await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp))).status,401);
  blocked=await auth.POST(request('incorrect',env.APP_ORIGIN,attackIp));assert.equal(blocked.status,429);assert.equal(blocked.headers.get('retry-after'),'4500');
 }finally{Date.now=originalNow;}
 assert.equal(db.prepare('SELECT owner FROM tasks').get().owner,'legacy-owner');
 db.close();delete globalThis.authFixture;delete process.env.APP_ORIGIN;delete process.env.ACCESS_CODE_SECRET;
});
