'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {Play,Pause,Square,Clock3,NotebookPen,Plus,RefreshCw} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
type Task={id:string;day:string;title:string;note:string;elapsed:number;started:number|null;status:string;version:number};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const duration=(ms:number)=>{const s=Math.floor(ms/1000);return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':');};
export default function Workspace(){
 const [day,setDay]=useState(today),[tasks,setTasks]=useState<Task[]>([]),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[error,setError]=useState(''),[auth,setAuth]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(''),[note,setNote]=useState(''),[minutes,setMinutes]=useState('0'),[edit,setEdit]=useState<Task|null>(null),[remove,setRemove]=useState<Task|null>(null),[message,setMessage]=useState('');
 const request=useRef(0),lock=useRef(false);
 const load=useCallback(async()=>{const seq=++request.current;try{const r=await fetch('/api/tasks?day='+day);const data=await r.json() as {tasks:Task[];now:number;error:string};if(seq!==request.current)return;if(r.status===401){setAuth(true);return;}if(!r.ok)throw Error(data.error);setAuth(false);setTasks(data.tasks);setOffset(data.now-Date.now());setError('');}catch(e){if(seq===request.current)setError(e instanceof Error?e.message:'연결을 확인해 주세요.');}finally{if(seq===request.current)setLoading(false);}},[day]);
 useEffect(()=>{void load();const id=setInterval(load,10000);const focus=()=>void load();window.addEventListener('focus',focus);return()=>{clearInterval(id);window.removeEventListener('focus',focus);request.current++;};},[load]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();try{Promise.resolve(ctx.registerTool({name:'read_work_records',description:'Read saved work records for a Korean calendar date.',inputSchema:{type:'object',properties:{day:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}},required:['day'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||!/^\d{4}-\d{2}-\d{2}$/.test(input.day))throw Error('Invalid date');const r=await fetch('/api/tasks?day='+input.day);const data=await r.json() as {tasks:Task[];now:number;error:string};if(!r.ok)throw Error(data.error);return data;}},{signal:controller.signal})).catch(console.error);}catch(e){console.error(e);}return()=>controller.abort();},[]);
 async function act(body:object){if(lock.current)return false;lock.current=true;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {tasks:Task[];now:number;error:string};if(!r.ok){if(r.status===409)await load();throw Error(data.error);}await load();setMessage('저장되었습니다.');return true;}catch(e){setError(e instanceof Error?e.message:'저장에 실패했습니다.');return false;}finally{lock.current=false;setBusy(false);}}
 const active=tasks.find(t=>t.status!=='done');const elapsed=(t:Task)=>t.elapsed+(t.started===null?0:Math.max(0,now+offset-t.started));const daily=tasks.filter(t=>t.day===day);const total=daily.reduce((s,t)=>s+elapsed(t),0);
 async function save(run:boolean){const ok=await act({action:edit?'edit':'create',id:edit?.id,version:edit?.version,title,note,day,elapsed:Math.round(Number(minutes)*60000),run});if(ok){setTitle('');setNote('');setMinutes('0');setEdit(null);}}
 return <div className="shell"><header className="top"><div className="brand"><Clock3/><strong>업무 기록</strong><span>WORK TIMER</span></div><span className="private">개인 작업 공간</span></header><main>
 <div className="heading"><div><p className="eyebrow">DAILY WORKSPACE</p><h1>하루의 일을 기록하세요.</h1></div><div className="date-controls"><label htmlFor="day">기록 날짜</label><input id="day" type="date" value={day} onChange={e=>{if(e.target.value){setDay(e.target.value);setEdit(null);}}}/><button onClick={()=>setDay(today())}>오늘</button></div></div>
 {auth&&<div className="notice">기록을 열려면 로그인해 주세요. <a href="/signin-with-chatgpt?return_to=%2F" target="_top">ChatGPT로 로그인</a></div>}
 {error&&<div className="notice error" role="alert">{error} <button onClick={()=>void load()}><RefreshCw size={16}/>다시 불러오기</button></div>}
 <div className="columns"><section className="timer-panel"><div className="panel-label"><Clock3 size={18}/><span>작업 스톱워치</span><span className="badge">{active?(active.status==='running'?'측정 중':'일시정지'):'준비'}</span></div><h2>{active?.title||'지금 집중할 작업'}</h2><div className="clock" role="timer">{duration(active?elapsed(active):0)}</div><p className="timer-note">{active?`${active.day} 시작 · 브라우저를 닫아도 기록이 유지됩니다.`:'아래에 작업을 입력하고 측정을 시작하세요.'}</p><div className="timer-actions">{active?<><button className="light" disabled={busy} onClick={()=>act({action:active.status==='running'?'pause':'resume',id:active.id,version:active.version})}>{active.status==='running'?<Pause size={18}/>:<Play size={18}/>} {active.status==='running'?'일시정지':'다시 시작'}</button><button className="outline" disabled={busy} onClick={()=>act({action:'finish',id:active.id,version:active.version})}><Square size={16}/>종료·저장</button></>:<span>한 번에 하나의 작업을 측정합니다.</span>}</div></section>
 <section className="summary"><p className="eyebrow">선택한 날짜의 기록</p><h2>오늘의 작업량</h2><strong className="total">{duration(total)}</strong><div className="summary-bottom"><span>기록한 작업 <b>{daily.length}개</b></span><span>완료 <b>{daily.filter(t=>t.status==='done').length}개</b></span></div><p>자정을 넘긴 작업은 시작 날짜에 합산됩니다.</p></section></div>
 <div className="content-grid"><section className="entry"><div className="section-title"><NotebookPen size={20}/><h2>{edit?'기록 수정':'새 작업'}</h2></div><form onSubmit={e=>{e.preventDefault();void save(false);}}><label>작업명<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="어떤 일을 하셨나요?"/></label><label>업무 내용<textarea maxLength={20000} value={note} onChange={e=>setNote(e.target.value)} placeholder="진행 내용, 결과, 다음 할 일을 남겨두세요." rows={5}/></label><label>소요 시간 (분)<input type="number" min="0" max="525600" step="0.01" required value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><p className="hint">직접 기록할 때 입력하세요. 측정 시작 시에는 0부터 시작합니다.</p><div className="form-actions">{!edit&&<button className="primary" type="button" disabled={busy||auth||loading||!!active||!title.trim()} onClick={()=>save(true)}><Play size={16}/>측정 시작</button>}<button className={edit?'primary':''} disabled={busy||auth||loading} type="submit"><Plus size={16}/>{edit?'수정 저장':'기록 저장'}</button>{edit&&<button type="button" onClick={()=>{setEdit(null);setTitle('');setNote('');setMinutes('0');}}>취소</button>}</div><p role="status" className="saved">{message}</p></form></section>
 <section className="records"><div className="section-title"><h2>업무 일지</h2><span>{day}</span></div>{loading?<p className="empty">기록을 불러오는 중입니다.</p>:daily.length===0?<div className="empty"><NotebookPen size={32}/><h3>아직 기록이 없습니다.</h3><p>작업을 시작하거나 완료한 업무를 남겨보세요.</p></div>:daily.map(t=><article className="record" key={t.id}><div className="record-head"><h3>{t.title}</h3><strong>{duration(elapsed(t))}</strong></div><span className="status">{t.status==='done'?'완료':t.status==='running'?'측정 중':'일시정지'}</span>{t.note&&<p className="note">{t.note}</p>}{t.status==='done'&&<div className="record-actions"><button disabled={busy} onClick={()=>{setEdit(t);setTitle(t.title);setNote(t.note);setMinutes(String(Math.round(t.elapsed/600)/100));}}>수정</button><button disabled={busy} onClick={()=>setRemove(t)}>삭제</button></div>}</article>)}</section></div><footer>한국 시간 기준 · 기록은 기기 간 자동 동기화됩니다.</footer>
 </main><AlertDialog open={!!remove} onOpenChange={open=>{if(!open)setRemove(null);}}><AlertDialogContent><AlertDialogTitle>이 기록을 삭제하시겠습니까?</AlertDialogTitle><AlertDialogDescription>“{remove?.title}”의 업무 내용과 측정 시간이 삭제됩니다.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction onClick={()=>{if(remove)void act({action:'delete',id:remove.id,version:remove.version});}}>삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
